import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {
  useEffect(()=>{
    // 함수컴포넌트가 화면에 처음 렌더링 될 때 - onMount
    // dependencies 에 할당된 값이 변했을 때 - onUpdate
    console.log( window );
    // SSR 에서는 동작하지 않는 영역
    fetch( '/menu.csv' )
      .then( res => res.text() )
      .then( text => {
        const result = text.split('\n').map( line => line.split(',') );
        console.log( result );
      } ); // AJAX

    axios.get( '/api/proxy' ).then( res => {
      console.log( res.data );
    } );

    axios.get('https://google.com')
      .then( res => console.log( 'loaded google' ) )
      .catch( () => console.warn( 'load error' ) );
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Home :: {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">{process.env.NEXT_PUBLIC_APP_NAME}</a>
        </h1>

        <form>
          <div>
            <input type="email" placeholder='E-mail' value={ process.env.NEXT_PUBLIC_DO_NOT_USE_IN_PRODUCTION_LOGIN_EMAIL || ''} />
          </div>
          <div>
            <input type="password" placeholder='Password' value={ process.env.NEXT_PUBLIC_DO_NOT_USE_IN_PRODUCTION_LOGIN_PASSWORD || ''} />
          </div>
          <div>
            <button>Login</button>
          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2022 {process.env.NEXT_PUBLIC_APP_NAME} | 
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
